#!/usr/bin/env python

import os
import sys
import copy
import subprocess32 as subprocess
import threading
import shutil
import csv
import time
import datetime
import mimetypes
import SimpleHTTPServer
import BaseHTTPServer
import urlparse
#import SocketServer
import matplotlib
matplotlib.use('agg')
matplotlib.rcParams['font.size'] = 19
import matplotlib.pyplot as pp
from matplotlib import dates
import argparse

global tstart
global nodes

### output from subprocess
# function 'check_output' redefined to enable the returning of output
def subprocess_check_output(*popenargs, **kwargs):
    timeout = kwargs.pop('timeout', None)
    if 'stdout' in kwargs:
        raise ValueError('stdout argument not allowed, it will be overridden.')
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
    try:
        output, unused_err = process.communicate(timeout=timeout)
    except subprocess.TimeoutExpired:
        process.kill()
        output, unused_err = process.communicate()
    #raise TimeoutExpired(process.args, timeout, output=output)
    retcode = process.poll()
    if retcode:
        raise subprocess.CalledProcessError(retcode, process.args, output=output)
    return output

### html update
def write_html_index():
  # requires global nodes and tstart variables!
  html = """
<!doctype html>
<meta http-equiv="refresh" content="%(iter)s" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!meta http-equiv="Location" content="/" />
<meta name="author" content="Sven E. Templer" />
<head>
  <title>slurm monitor</title>
  <link rel="shortcut icon" type="image/png" href="favicon.png"/>
  <style>
    html { box-sizing: border-box; }
    *,::before,::after { box-sizing: inherit; }
    body { width: 96%%; font-family: sans-serif; color: #333333; margin: 15px; vertical-align: middle; }
    header,nav,main { border-radius: 0.5em 0.5em 0.5em; border: 1px solid; margin: 5px; padding: 5px;
      text-align: center; font-family: "Courier", Courier, monospace; }
    header { height: 90px; }
    header img { height: 80px; width: 80px; float: right;
      border:0px solid; -webkit-border-radius: 20px; -moz-border-radius: 20px; border-radius: 20px; }
    main img { height: 160px; width: 300px; margin: 5px; }
    nav { float: left; width: 150px; background: #fffbf0; border-color: #e7c157; margin-top: 0px; }
    nav li { list-style: circle; margin: 5px; text-align: left; }
    main { display: block; background: #c4ced3; border-color: #8a9da8; margin-top: 5px; }
    table { width:95%%; margin-left:auto; margin-right:auto; }
    tr { text-align: left; } 

    div.tabs {
      min-height: 100em; 
      margin: 10px;
      position: relative; 
      line-height: 1; 
      z-index: 0}  
    div.tabs > div {
      display: inline} 
    div.tabs > div > a {
      color: black; 
      background: #CCC;
      padding: 0.2em;
      border: 0.1em outset #BBB;
      border-bottom: 0.1em solid #CCC}
    div.tabs > div:not(:target) > a {
      border-bottom: none;
      background: #999}
    div.tabs > div:target > a, :target #tab3 > a {
      border-bottom: 0.1em solid #CCC;
      background: #CCC}
    div.tabs > div > div {
      background: #CCC;
      z-index: -2;
      left: 0; top: 1.3em;
      bottom: 0; right: 0;
      overflow: auto;
      padding: 0.3em;
      border: 0.1em}
    div.tabs > div:not(:target) > div {
      position: absolute }
    div.tabs > div:target > div, :target #tab3 > div {
      position: absolute;
      z-index: -1}
    div.tabs :target {
      outline: none}
  </style>
</head>
<body>
<header>
  <img src="avatar.png">
  <h1>slurm monitor</h1>
</header>
<!-- <nav>
  <h2>Update</h2>
  <ul>
  <li>Started:</br>%(zero)s</li>
  <li>Refreshed:</br>%(current)s</br>(%(iter)s sec auto)</li>
  <li>Slurm queue</br>(run/pend)</br>%(queue)s</li>
  </ul>
  <h2>Legend</h2>
  <ul>
  <li><font color="#0080FF">CPU</font></li>
  <li><font color="#FFBF00">RAM</font></li>
  <li><font color="#DF0101">Swap</font></li>
  </ul>
</nav> -->
<main>
  <div class=tabs>

    <div id=tab1>
      <a href="#tab1">Load</a> 
      <div>
        <p>monitoring started at %(zero)s / updated at %(current)s</p>
        <h2>Nodes Load</h2>
        <p>%(imgs)s</p>
      </div>
    </div>


    <div id=tab2>
      <a href="#tab2">Allocation</a>
      <div>
        <p>monitoring started at %(zero)s / updated at %(current)s</p>
        <h2>Slurm Allocation</h2>
        <p>%(load)s</p>
      </div>
    </div>

    <div id=tab3>
      <a href="#tab3">Jobs</a>
      <div>
        <p>monitoring started at %(zero)s / updated at %(current)s</p>
        <h2>Slurm Jobs</h2>
        <p>jobs running/pending: %(queue)s</p>
        <p>%(jobs)s</p>
      </div>
    </div>


  </div>
</main>
</body>
</html>"""
  queue = get_slurmqueue()
  load = get_slurmload()
  jobs = get_slurmqueue_table()
  tnow = time.strftime('%Y-%m-%d %H:%M:%S')
  imgs = [ '<img src="svg/' + node + '.svg" alt="' + node + '">' for node in nodes ]
  imgs = '\n'.join(imgs)
  f = open('index.html', 'w')
  f.write(html % { 'iter' : 60, 'zero' : tstart, 
    'current' : tnow, 'queue' : queue, 'load' : load, 'imgs' : imgs, 'jobs' : jobs })
  f.close()

### http handler with custom index.html
# extended default do_GET from SimpleHTTPRequestHandler
# to create 'index.html' file with custom variable values inserted:
def handler_get_method(self):
  g_plotrange = urlparse.parse_qs(
      urlparse.urlparse(self.path).query).get('r', 60)
  write_html_index()
  f = self.send_head()
  if f:
    try:
      self.copyfile(f, self.wfile)
    finally:
      f.close()

### get http handler
def handler():
  h = SimpleHTTPServer.SimpleHTTPRequestHandler
  h.do_GET = handler_get_method
  h.extensions_map['.svg']='image/svg+xml'
  return h

### get slurm queue
def get_slurmqueue ():
  cmd = [ 'squeue', '-o', '%T' ]
  try:
    jobs = subprocess.check_output(cmd, stderr = subprocess.STDOUT, timeout = 3)
  except:
    jobs = 'STATE\n'
    pass
  jobs = jobs.split('\n')
  npend = len([i for i in jobs if i == "PENDING"])
  nrun  = len([i for i in jobs if i == "RUNNING"])
  return str(nrun) + '/' + str(npend)

def as_html_table (x):
  x = x.split('\n')
  x = [ i.split(' ') for i in x if len(i) > 0 ]
  tab = '<table style>\n'
  for i in x:
    tab += '<tr>\n<td>'
    tab += '</td>\n<td>'.join(i)
    tab += '</td>\n</tr>\n'
  tab += '</table>'
  return tab

def get_slurmqueue_table ():
  try:
    jobs1 = subprocess.Popen(['squeue', "--sort=-T,-M", '-o', "%.7i %9P %12j %8u %.5T %.11M %.6C %18R"], 
    #jobs1 = subprocess.Popen(['squeue'], 
        stdout = subprocess.PIPE)
    jobs2 = subprocess.Popen(['sed', '-e', 's|^\ \+||', '-e', 's|\ \+|\ |g'],
        stdin = jobs1.stdout, stdout = subprocess.PIPE)
    jobs, err = jobs2.communicate()
  except:
    jobs = 'NA'
    pass
  queuestring = as_html_table(jobs)
  return queuestring

def get_slurmload ():
  try:
    load1 = subprocess.Popen(['sinfo', '-o', '%20n %10P %10T %15C %.7m'], 
        stdout = subprocess.PIPE)
    #load2 = subprocess.Popen(['tail', '-n', '+2'], stdin = load1.stdout, stdout = subprocess.PIPE)
    load3 = subprocess.Popen(['awk', '{split($4,a,"/"); $4=a[1]"/"a[4]; if ($5 ~ /^[0-9]+/ ) {$5=int($5/1024)"GB"}; print }'], 
        stdin = load1.stdout, stdout = subprocess.PIPE)
    load4 = subprocess.Popen(['sort'], stdin = load3.stdout, stdout = subprocess.PIPE)
    load, err = load4.communicate()
  except:
    load = 'NA'
    pass
  loadstring = as_html_table(load)
  return loadstring

### daemon stats
def rund_stats(home, nodes, sleep, user):
  script = """
cd %(home)s
while true
do
  line="$(date +%%Y-%%m-%%d_%%H:%%M:%%S) "
  line+="$(mpstat %(interval)s 1 | awk '$2=="all" && $1!="Average:" {print $3}') "
  line+="$(free | awk '/^Mem/{ mem=$3/$2*100 } /^Swap/{ swp=$3/$2*100 } END { print mem " " swp }')"
  echo "$line" >> stat/%(node)s
  sed -i -e :a -e '$q;N;%(length)s,$D;ba' stat/%(node)s
  sleep %(sleep)s
done""" 
  for node in nodes:
    f = open(home + '/sh/' +node, 'w')
    f.write(script % { 'home' : home, 'interval' : args.interval, 'node' : node, 'sleep' : args.sleep, 'length' : args.length })
    f.close()
    cmd = 'ssh ' + user + '@' + node + ' bash ' + home + '/sh/' + node
    proc = subprocess.Popen(cmd, shell = True)

### generate plot
def plot_load(home, node):
  d = csv.reader(open(home + '/stat/' + node), delimiter = ' ')
  dt = [] # time
  dc = [] # cpu load
  dm = [] # mem load
  ds = [] # swap load
  for row in d:
    dt.append(datetime.datetime.strptime(row[0], '%Y-%m-%d_%H:%M:%S'))
    dc.append(float(row[1]))
    dm.append(float(row[2]))
    ds.append(float(row[3]))
  #i0 = len
  dx = range(len(dt))
  fig, ax = pp.subplots(1)
  fig.set_size_inches(12, 6) # x=4.8 y=1.6
  ax.set_ylim(0, 100)
  ax.set_title(node)
  ax.set_ylabel('[%]')
  ax.set_xlabel('Time')
  ax.fill_between(dt, float(0), dc, facecolor='blue', alpha='.6')
  ax.plot(dt,dm,color='orange', lw = 5)
  ax.plot(dt,ds,color='red', lw = 3)
  fig.autofmt_xdate(rotation=25)
  ax.xaxis.set_major_formatter(dates.DateFormatter('%H:%M:%S'))
  fig.savefig('svg/' + node + '.svg', format='svg') # dpi = 300
  pp.close()

### daemon plots
def rund_plots(home, nodes, sleep):
  while 1:
    for node in nodes:
      if not os.path.isfile(home + '/stat/' + node):
        continue
      time.sleep(.5)
      plot_load(home, node)
    time.sleep(sleep)

### write nginx.config
def write_nginx_conf (home, port, host):
  cfg = """
# nginx -c /path/to/this/slurmon.nginx.conf
error_log %(home)s/error.log;
pid %(home)s/nginx.pid;
worker_processes 1;
events {
  worker_connections 1024;
}
http {
  client_body_temp_path %(home)s/client_body;
  fastcgi_temp_path %(home)s/fastcgi_temp;
  proxy_temp_path %(home)s/proxy_temp;
  scgi_temp_path %(home)s/scgi_temp;
  uwsgi_temp_path %(home)s/uwsgi_temp;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  include /etc/nginx/mime.types;
  index index.html;
  log_format   main '$remote_addr - $remote_user [$time_local] $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  default_type application/octet-stream;
  server {
    listen %(host)s:%(port)s;
    access_log %(home)s/access.log;
    error_log %(home)s/error.log;
    root %(home)s/;
    index index.html;
    sendfile on;
    location / { deny all; }
    location = / { }
    location = /index.html { }
    location = /favicon.png { }
    location = /avatar.png { }
    location /svg { allow all; sendfile on; }
  }
}
"""
  f = open('nginx.conf', 'w')
  f.write(cfg % { 'home' : home, 'port' : port, 'host' : host })
  f.close()
  
### nginx thread
def rund_nginx (home, port, host):
  write_nginx_conf(home, port, host)
  cmd = ['nginx', '-c', home + 'nginx.conf', '-p', home]
  print('running nginx as: ' + ' '.join(cmd))
  proc = subprocess.Popen(cmd)

### check tmp dir tree
def create_home(home):
  pwd = os.getcwd()
  try:
    shutil.rmtree(home)
  except:
    print('warning: could not remove server directory ' + home)
  try:
    os.makedirs(home)
    os.makedirs(home + '/svg')
    os.makedirs(home + '/sh')
    os.makedirs(home + '/stat')
  except:
    print('error: could not create working directory ' + home)
    quit()
  shutil.copy(pwd + '/favicon.png', home) 
  shutil.copy(pwd + '/avatar.png', home) 
  try:
    os.chdir(home)
    print('changed to working directory ' + home)
  except:
    print('error: could not change to working directory ' + home)
    quit()
 
### run
if __name__ == '__main__':
  parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument('-n', '--nodes', help='host names to query', default = ['cluster'], nargs='+')
  parser.add_argument('-s', '--sleep', help='sleep time between queries', default = 60)
  parser.add_argument('-i', '--interval', help='stats query interval', default = 3)
  parser.add_argument('-l', '--length', help='number of timepoints/queries to plot', default = 30)
  parser.add_argument('-p', '--port', help='http server port', default = 8910)
  parser.add_argument('-d', '--home-directory', help='shared directory', dest = 'home', default = '~/.slurmon')
  parser.add_argument('-u', '--user', help='ssh user, default is current')
  parser.add_argument('-x', '--nginx', help='run as nginx daemon', action = 'store_true')
  args = parser.parse_args()
  pid = os.getpid()
  args.home += '/' + str(pid) + '/' 
  args.home = os.path.expanduser(args.home)
  nodes = args.nodes
  for n in nodes:
    print('adding node:' + n)
  #nodes = args.nodes.split(',')
  host = os.uname()[1]
  if args.user is None:
    args.user = os.getenv('USER')
  handler = handler()
  subprocess.check_output = subprocess_check_output
  print('creating home ...')
  create_home(args.home)
  print('starting statistics daemon ...')
  daemon_stats = threading.Thread(target = rund_stats, args = [args.home, nodes, args.sleep, args.user])
  daemon_stats.daemon = True
  daemon_stats.start()
  print('starting plot daemon ...')
  daemon_plots = threading.Thread(target = rund_plots, args = [args.home, nodes, args.sleep])
  daemon_plots.daemon = True
  daemon_plots.start()
  tstart = time.strftime('%Y-%m-%d %H:%M:%S')
  print('starting webserver daemon (host:port = %s:%s) at ' % (host, args.port) + tstart) #time.asctime()
  if args.nginx:
    server_nginx = threading.Thread(target = rund_nginx, args = [args.home, args.port, host])
    server_nginx.daemon = True
    server_nginx.start()
    try:
      while True:
        write_html_index()
        time.sleep(10)
    except KeyboardInterrupt:
      pass
  else:
    server_base = BaseHTTPServer.HTTPServer((host, args.port), handler)
    try:
      server_base.serve_forever()
    except KeyboardInterrupt:
      pass
    server_base.server_close()
  print "stopping daemons ..."
  try:
    shutil.rmtree(args.home)
  except:
    print('warning: could not remove server directory ' + args.home)
  try:
    os.remove('index.html')
  except:
    print('warning: could not remove index.html')
    quit()

### EOF
